name: Pack Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        
      - name: Setup NPM packages
        run: npm install
        
      - name: Pack extension
        run: npm run build
        
      - name: Upload for Firefox
        uses: actions/upload-artifact@v3.1.2
        with:
          name: OldTwitterFirefox
          path: D:\a\OldTwitter\OldTwitterFirefox.zip
      - name: Upload for Chromium
        uses: actions/upload-artifact@v3.1.2
        with:
          name: OldTwitterChrome
          path: D:\a\OldTwitter\OldTwitterChrome.zip
