name: Pack Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        
      - name: Setup NPM packages
        run: npm install
        
      - name: Pack extension
        run: npm run build

      - name: Unzip extension
        uses: montudor/action-zip@v1.0.0
        with:
          args: unzip -qq ${{ github.workspace }}/../OldTwitterChrome.zip -d ${{ github.workspace }}/../OldTwitterChrome; unzip -qq ${{ github.workspace }}/../OldTwitterFirefox.zip -d ${{ github.workspace }}/../OldTwitterFirefox
        
      - name: Upload for Firefox
        uses: actions/upload-artifact@v3.1.2
        with:
          name: OldTwitterFirefox.zip
          path: ${{ github.workspace }}/../OldTwitterFirefox
      - name: Upload for Chromium
        uses: actions/upload-artifact@v3.1.2
        with:
          name: OldTwitterChrome.zip
          path: ${{ github.workspace }}/../OldTwitterChrome
